#lang sicp

(define (cube x) (* x x x))
(define (p x) (- (* 3 x) (* 4 (cube x))))
(define (sine angle)
   (if (not (> (abs angle) 0.1))
       angle
       (p (sine (/ angle 3.0)))))

; How many times is the procedure p applied when (sine 12.15) is evaluated?
; 5 times (12.15 / 3 = 4.05 / 3 = 1.35 / 3 = 0.45 / 3 = 0.15 / 3 = 0.05)

; What is the order of growth in space and number of steps (as a function of a ) 
; used by the process generated by the sine procedure when (sine a) is evaluated? 
; log(a) - since each time a is divided by 3, if we compute for 9a,then its just
; 2 extra steps to get to a.